apiVersion: v1
kind: Service
metadata:
  name: taxiagent-order-service
  namespace: taxiagent
spec:
  type: ClusterIP
  selector:
    app: taxiagent-order-service
  ports:
    - name: http
      port: 8083
      targetPort: http
