apiVersion: v1
kind: Service
metadata:
  name: taxiagent-user-service
  namespace: taxiagent
spec:
  type: ClusterIP
  selector:
    app: taxiagent-user-service
  ports:
    - name: http
      port: 8081
      targetPort: http
