CREATE TABLE `sys_ride_order` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_id` BIGINT NOT NULL COMMENT '订单ID',
    `user_id` BIGINT NOT NULL COMMENT '乘客用户ID',
    `driver_id` BIGINT DEFAULT NULL COMMENT '司机ID (接单后回填)',
    `mongo_trace_id` VARCHAR(64) DEFAULT NULL COMMENT '关联MongoDB的轨迹ID',
    `vehicle_type` INT DEFAULT 1 COMMENT '车辆类型 (1:快车, 2:优享, 3:专车)',
    `is_reservation` TINYINT(1) DEFAULT 0 COMMENT '是否为预约单 (0:否, 1:是)',
    `is_expedited` TINYINT(1) DEFAULT 0 COMMENT '是否加急 (0:否, 1:是)',
    `safety_code` CHAR(4) DEFAULT NULL COMMENT '安全码 (乘客上车核销用)',
    `order_status` TINYINT NOT NULL DEFAULT 10 COMMENT '状态: 10-创建, 20-司机接单, 30-司机到达, 40-行程中, 50-完成待支付, 60-已支付, 90-已取消',
    `cancel_role` TINYINT DEFAULT NULL COMMENT '取消方: 1-用户, 2-司机, 3-系统',
    `cancel_reason` VARCHAR(255) DEFAULT NULL COMMENT '取消原因',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下单时间',
    `scheduled_time` DATETIME DEFAULT NULL COMMENT '预约上车时间',
    `driver_accept_time` DATETIME DEFAULT NULL COMMENT '司机接单时间',
    `driver_arrive_time` DATETIME DEFAULT NULL COMMENT '司机到达起点时间',
    `pickup_time` DATETIME DEFAULT NULL COMMENT '开始行程/上车时间',
    `finish_time` DATETIME DEFAULT NULL COMMENT '结束行程/下车时间',
    `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
    `start_address` VARCHAR(255) DEFAULT NULL COMMENT '起点地址',
    `start_lat` DECIMAL(10, 6) DEFAULT NULL COMMENT '起点纬度',
    `start_lng` DECIMAL(10, 6) DEFAULT NULL COMMENT '起点经度',
    `end_address` VARCHAR(255) DEFAULT NULL COMMENT '终点地址',
    `end_lat` DECIMAL(10, 6) DEFAULT NULL COMMENT '终点纬度',
    `end_lng` DECIMAL(10, 6) DEFAULT NULL COMMENT '终点经度',
    `est_distance` DECIMAL(10, 2) DEFAULT NULL COMMENT '预估距离(Km)',
    `real_distance` DECIMAL(10, 3) DEFAULT NULL COMMENT '实际距离(Km)',
    `est_price` DECIMAL(10, 2) DEFAULT NULL COMMENT '预估一口价',
    `real_price` DECIMAL(10, 2) DEFAULT NULL COMMENT '实际最终车费',
    `price_base` DECIMAL(10, 2) DEFAULT 0.00 COMMENT '基础里程费',
    `price_time` DECIMAL(10, 2) DEFAULT 0.00 COMMENT '时长费',
    `price_distance` DECIMAL(10, 2) DEFAULT 0.00 COMMENT '远途/空驶费',
    `price_expedited` DECIMAL(10, 2) DEFAULT 0.00 COMMENT '加急费',
    `price_radio` DECIMAL(10, 2) DEFAULT 0.00 COMMENT '乘算比例',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT(1) DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_id` (`order_id`),
    KEY `idx_user_create_time` (`user_id`, `create_time`),
    KEY `idx_status_create_time` (`order_status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网约车订单表';
