apiVersion: v1
kind: Service
metadata:
  name: taxiagent-gateway
  namespace: taxiagent
spec:
  type: ClusterIP
  selector:
    app: taxiagent-gateway
  ports:
    - name: http
      port: 9000
      targetPort: http
