apiVersion: v1
kind: Service
metadata:
  name: taxiagent-ticket-service
  namespace: taxiagent
spec:
  type: ClusterIP
  selector:
    app: taxiagent-ticket-service
  ports:
    - name: http
      port: 8084
      targetPort: http
